# Generated by Django 4.1.3 on 2025-05-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamer',
            name='bio',
            field=models.TextField(max_length=50),
        ),
    ]
